const addons = [
  '@eeacms/volto-eea-kitkat',
  '@eeacms/volto-redirector',
  '@eeacms/volto-editing-progress',
  '@eeacms/volto-workflow-progress',
  '@eeacms/volto-embed',
  '@eeacms/volto-embed-static-content',
  '@eeacms/volto-embed-content',
  '@eeacms/volto-datablocks',
  '@eeacms/volto-plotlycharts',
  '@eeacms/volto-eea-map',
  '@eeacms/volto-tableau',
  '@eeacms/volto-block-data-figure',
  '@eeacms/volto-redmine-helpdesk',
  '@eeacms/volto-searchlib',
  '@eeacms/volto-globalsearch',
  '@eeacms/volto-datahub',
  '@eeacms/volto-eea-versions',
  '@eeacms/volto-eea-design-system',
  '@eeacms/volto-eea-website-theme',
  '@eeacms/volto-eea-website-policy',
  '@eeacms/volto-eea-chatbot',
  '@plone-collective/volto-authomatic',
  '@eeacms/volto-citation',
  '@eeacms/volto-flourish',
  'volto-subsites',
  '@plone-collective/volto-rss-provider',
  'eea-website-frontend',
];

module.exports = {
  addons,
  theme: '@eeacms/volto-eea-website-theme',
};
